version: '3.1'
services:
  mongo:
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: unzahssa
      MONGO_INITDB_ROOT_DATABASE: unzahssa-db
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27018:27017'
    volumes:
      - 'mongo-db:/data/unzahssa-db'
  unzahssa-app:
    build: .
    restart: always
    expose:
      - '3000'
    depends_on:
      - mongo
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80' # Map host port 80 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mount your custom NGINX config
    depends_on:
      - unzahssa-app # Ensure NGINX starts after Next.js
volumes:
  mongo-db:
