version: '3.1'
services:
  mongo:
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: unzahssa
      MONGO_INITDB_ROOT_DATABASE: unzahssa-db
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27018:27017'
    volumes:
      - 'mongo-db:/data/unzahssa-db'
volumes:
  mongo-db:
